Forum page topics api
CotripperPlatform/CoTrip pull request #653
Opened 2020-07-07 14:50 UTC by Bcastillo44

- Related Issue (include '#'): #652

- Description of changes made:
Created connection topics from API to topics of interest on Forum page 

- Is the feature complete/bug resolved/etc..:

Not all topics are being pulled from API, need to resolve

2020-07-09 13:54 UTC, 0xZakk requested changes
@Bcastillo44 It looks like a lot of these are from your other PR - can you make it so this PR only has the code relevant to the issue it's for? Each PR should only have the code for a single user story or issue

2020-07-09 13:54 UTC, ZakkMan commented on api/community/fixtures/community.json
> +  },
These fixtures look good!

2020-07-09 13:54 UTC, ZakkMan commented on client/src/components/CarouselDots/CarouselDots.js
> +// import ReactDOM from "react-dom";
Can you delete any commented out code?

2020-07-10 18:09 UTC, 0xZakk requested changes
@Bcastillo44 Looks good! Just a few small changes

2020-07-10 18:09 UTC, ZakkMan commented on client/src/pages/ForumPage/ForumPage.js
> +}
Can you put this in the appropriate service in the `services/` directory?

2020-07-10 18:09 UTC, ZakkMan commented on client/src/pages/ForumPage/ForumPage.js
> +        <a href className="secondNav">
Do you need this href? Should it have a value?

2020-07-14 17:51 UTC, 0xZakk requested changes
Can you fix this page? It's really important that you test your work before making a PR

<img width="1904" alt="Screen Shot 2020-07-14 at 1 50 56 PM" src="https://user-images.githubusercontent.com/4991553/87459177-0c1ca380-c5d9-11ea-99fa-a3a39df48c73.png">

2020-07-15 03:27 UTC, secondaryfun commented
Branch https://github.com/CotripperPlatform/CoTrip/pull/685 has these changes. This branch can be closed without merging.

2020-07-15 13:12 UTC, closed without merging