Display groups im in
CotripperPlatform/CoTrip pull request #655
Opened 2020-07-08 02:12 UTC by WRNoble

- Related Issue (include '#'): #441

- Description of changes made:

- Is the feature complete/bug resolved/etc..:

- Any known bugs/strange behavior:

- Is there specific feedback you would like on these changes:

- Screenshot(s):

2020-07-10 18:28 UTC, 0xZakk requested changes
@WRNoble Looks good! See my feedback

2020-07-10 18:28 UTC, ZakkMan commented on Pipfile
> +[[source]]
Can you delete this pipfile?

2020-07-10 18:28 UTC, ZakkMan commented on client/src/App.js
> +import GroupPage from "./components/GroupPage/GroupPage"
Are you using this page somewhere? Should there be a route for it?

2020-07-10 18:28 UTC, ZakkMan commented on client/src/components/GroupPage/GroupPage.css
> +}
Can you update the CSS here so it's inline with the conventions in the README?

2020-07-10 18:28 UTC, ZakkMan commented on client/src/components/GroupPage/GroupPage.js
> +import React from 'react';
Why is this page in the components directory and not the pages directory?

2020-07-10 18:28 UTC, ZakkMan commented on client/src/components/GroupPage/GroupPage.js
> +                />
Should these be coming from the API?

2020-07-10 18:28 UTC, ZakkMan commented on client/src/components/GroupPage/GroupPage.js
> +            <div className="HomePage__group-cards-container">
Where are these classes coming from?

2020-07-10 18:28 UTC, ZakkMan commented on client/src/pages/DirectoryPage/DirectoryGroups.js
> +  }
Can you put this in the appropriate service in the `services/` directory? All AJAX requests should be in a service

2020-07-10 18:28 UTC, ZakkMan commented on client/src/pages/DirectoryPage/DirectoryGroups.js
> +    console.log(this.state)
Be sure to delete all commented out code and any `console.log` or `print` statements before making a PR going forward

2020-07-10 18:28 UTC, ZakkMan commented on client/src/pages/DirectoryPage/DirectoryGroups.js
> +          <div className="CommunityPage__group-location-container">
We decided to remove this Pill section right?

2020-07-10 18:28 UTC, ZakkMan commented on client/src/pages/DirectoryPage/DirectoryGroups.js
> +          <a className="seeMore-Button">See More</a>
Can you use names inline with the naming convention described in the README?

2020-07-10 18:28 UTC, ZakkMan commented on client/src/pages/DirectoryPage/DirectoryGroups.js
> +            console.log(group)
Delete

2020-07-15 04:35 UTC, secondaryfun commented
The updates from this branch have been incorporated into https://github.com/CotripperPlatform/CoTrip/pull/654 .  This branch can be closed without merging.

2020-07-15 13:05 UTC, closed without merging