Change user password
CotripperPlatform/CoTrip pull request #673
Opened 2020-07-13 14:17 UTC by Las6103

- Related Issue (include '#'): #425 

- Description of changes made:
This branch contains Chris's social media adjustments as well as the password change feature.
- Is the feature complete/bug resolved/etc..:
The password feature is complete and fully functional
- Any known bugs/strange behavior:
NA
- Is there specific feedback you would like on these changes:
NA
- Screenshot(s):

2020-07-13 14:59 UTC, 0xZakk requested changes
Rather than have an alert pop down, can you display a message in UI? If the password is successfully changed, we should replace the form with a success message. If there's an error, then display that error with the form.

Also, can we do it without the email field? You can pull the email from the current user who is signed in. You want to check the JWT to verify auth anyway, rather than effectively have them re-sign in.

2020-07-13 14:59 UTC, ZakkMan commented on client/src/components/Bio/Bio.css
> +}
Can you use the CSS naming convention?

2020-07-15 13:22 UTC, 0xZakk requested changes
Add labels to inputs and then merge it

2020-07-15 17:12 UTC, Las6103 commented
Merging the request. No conflicts.

2020-07-15 17:12 UTC, merged