Member profile completion
CotripperPlatform/CoTrip pull request #679
Opened 2020-07-13 22:08 UTC by know-mad

- Related Issue (include '#'):
#421 
- Description of changes made:
Made the user profile picture, hashtags, and contacts all render from the user account in the api
- Is the feature complete/bug resolved/etc..:
still working on the trips to render from the api as well
- Any known bugs/strange behavior:
n/a
- Is there specific feedback you would like on these changes:

- Screenshot(s):

2020-07-14 17:45 UTC, 0xZakk requested changes
@know-mad

2020-07-14 17:45 UTC, 0xZakk commented on client/src/components/InputTextField/InputTextField.js
> +  if (props.loadcallback && props.loadcallbackarg) props.loadcallback(props.loadcallbackarg);
You should format all your conditionals with brackets rather than in a single line like this

2020-07-14 17:45 UTC, 0xZakk commented on client/src/pages/MemberProfilePage/MemberProfilePage.js
> +				{
Can you put this in a service? Every ajax request should go in a service in the `services/` directory?

2020-07-14 17:45 UTC, 0xZakk commented on client/src/pages/MemberProfilePage/MemberProfilePage.js
> +					console.log('axios ', res.data)
Can you delete this and any other `console.log` statements?

2020-07-14 17:45 UTC, 0xZakk commented on client/src/pages/MemberProfilePage/MemberProfilePage.js
> +		// .then(res => console.log('axios ', res.data))
Delete this and any other commented out code

2020-07-14 17:45 UTC, 0xZakk commented on client/src/pages/MemberProfilePage/MemberProfilePage.js
> +						{" "}
Your formatting is weird here - can you make sure you have VS Code setup with prettier to auto format on save and on paste?

2020-07-14 17:45 UTC, 0xZakk commented on client/src/pages/MemberProfilePage/MemberProfilePage.js
> +		}
I don't think you need this - Pretty sure we take care of this in the routes

2020-07-14 17:45 UTC, 0xZakk commented on client/src/components/Bio/Bio.js
> +			data: {
Can you put this ajax request in a service?

2020-07-14 17:45 UTC, 0xZakk commented on client/src/components/Bio/Bio.js
> +		axios.get(`${BASE_URL}/social_media_type`,
This one too re the services - all ajax requests should be in a service

2020-07-14 20:25 UTC, secondaryfun commented
@know-mad @ZakkMan  It looks like many of the requested changes here will be addressed once https://github.com/CotripperPlatform/CoTrip/pull/646 has been brought into develop.  Specifically, the ajax calls.

2020-07-15 13:26 UTC, 0xZakk requested changes
Merge develop and chris' branch into this branch, double check everything

2020-07-15 17:49 UTC, closed without merging